// This file is part of Compact.
// Copyright (C) 2025 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import inspect from 'object-inspect';

/**
 * An error originating from code generated by the Compact compiler
 */
export class CompactError extends Error {
  readonly isCompactError = true;

  constructor(msg: string) {
    super(msg);
    this.name = 'CompactError';
  }

  /**
   * Recognizes instances across copies of this package, subclasses included, where `instanceof`
   * would not: a generated contract module resolves the runtime from its own location, so the copy
   * that throws is not the copy an application catches with.
   */
  static is(u: unknown): u is CompactError {
    return typeof u === 'object' && u !== null && (u as { isCompactError?: unknown }).isCompactError === true;
  }
}

/**
 * Compiler internal for assertions
 * @internal
 */
export function assert(b: boolean, s: string): void {
  if (!b) {
    const msg = `failed assert: ${s}`;
    throw new CompactError(msg);
  }
}

/**
 * Compiler internal for asserting an object is non-nullable.
 * @internal
 */
export function assertDefined<T>(t: T | undefined, name: string): asserts t is NonNullable<T> {
  if (t === undefined || t === null) {
    throw new CompactError(`Expected ${name} to be defined`);
  }
}

/**
 * Compiler internal for asserting an object is nullable.
 * @internal
 */
export function assertUndefined(t: any, name: string): void {
  if (t !== undefined && t !== null) {
    throw new CompactError(`Expected ${name} to be undefined`);
  }
}

/**
 * Compiler internal for type errors
 * @internal
 */
export function typeError(who: string, what: string, where: string, type: string, x: any): never {
  const msg = `type error: ${who} ${what} at ${where}; expected value of type ${type} but received ${inspect(x)}`;
  throw new CompactError(msg);
}
