name: Testing runtime

on:
  workflow_dispatch:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout compactc repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Nix with cache
        uses: ./.github/actions/setup-nix-cache
        with:
          attic_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Setup .npmrc
        run: |
          cd ./runtime
          echo "
          //npm.pkg.github.com/:_authToken=${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
          @midnight-ntwrk:registry=https://npm.pkg.github.com/
          " > .npmrc

      - name: Configure yarn
        run: |
          cd ./runtime
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}"
          echo 'checksumBehavior: update' >> ./.yarnrc.yml

      - name: Build lib
        run: |
          nix build .#runtime.forPublish

      - name: Build and test
        run: |
          nix develop --command bash -c "cd ./runtime ; npm run build ; npm run test"
