name: Check documentation versions

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to check documentation on'
        required: true
        type: string
    secrets:
      MIDNIGHTCI_PACKAGES_WRITE:
        required: false

permissions: {}

jobs:
  check-docs:
    name: Check if documentation is updated
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout compactc repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Check compiler and language versions in internal documentation
        run: |
          # check compiler version
          COMPILER_VERSION=$(grep -oP "\(make-version 'compiler \K[0-9 ]+" compiler/compiler-version.ss | tr ' ' '.')
          DOCS_COMPILER=$(grep -oP "compiler version \K[0-9]+\.[0-9]+\.[0-9]+" doc/ledger-adt.mdx)

          echo "Compiler version: $COMPILER_VERSION"
          echo "Compiler version in docs: $DOCS_COMPILER"

          if [ "$COMPILER_VERSION" != "$DOCS_COMPILER" ]; then
            echo "Compiler version mismatch, please update"
            exit 1
          fi

          echo "Compiler versions match"

          # check language version
          LANGUAGE_VERSION=$(grep -oP "\(make-version 'language \K[0-9 ]+" compiler/language-version.ss | tr ' ' '.')
          DOCS_LANGUAGE=$(grep -oP "language version \K[0-9]+\.[0-9]+\.[0-9]+" doc/ledger-adt.mdx)

          echo "Language version: $LANGUAGE_VERSION"
          echo "Language version in docs: $DOCS_LANGUAGE"

          if [ "$LANGUAGE_VERSION" != "$DOCS_LANGUAGE" ]; then
            echo "Language versions mismatch, please update"
            exit 1
          fi

          echo "Language versions match"
