name: Agda Formal Verification

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify Agda Specifications
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        name: Cache cabal packages
        id: cache-cabal
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            ~/.cabal/bin
            dist-newstyle
          key: ${{ runner.os }}-cabal-packages

      - name: Set up Haskell (GHC and Cabal)
        uses: haskell-actions/setup@6037f33647c3f17758a2356c80fc4a53d7e0685d # v2.12.0
        with:
          ghc-version: "9.4.8"
          cabal-version: "3.10.3.0"

      - name: Put cabal programs in PATH
        run: echo "~/.cabal/bin" >> $GITHUB_PATH

      - name: Build Syntax Generation Tool
        run: |
          cd specification/syntax-generation
          cabal update
          cabal build
          cabal run

      - name: Set up Agda
        run: |
          cabal update
          test -e ~/.cabal/bin/agda || cabal install Agda


      - name: Check Agda Version
        run: agda --version

      - name: Checkout agda-stdlib-meta repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: agda/agda-stdlib-meta
          path: agda-stdlib-meta
          
      - name: Checkout agda-stdlib repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: agda/agda-stdlib
          ref: v2.3
          path: agda-stdlib

      - name: Checkout agda-stdlib-classes repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: agda/agda-stdlib-classes
          path: agda-stdlib-classes

      - name: Checkout iog-agda-prelude repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: input-output-hk/iog-agda-prelude
          path: iog-agda-prelude

      - name: Set agda configuration
        run: |
          mkdir ~/.agda || true
          echo "${{ github.workspace }}/agda-stdlib-meta/agda-stdlib-meta.agda-lib" >> ~/.agda/libraries
          echo "${{ github.workspace }}/agda-stdlib/standard-library.agda-lib" >> ~/.agda/libraries
          echo "${{ github.workspace }}/agda-stdlib-classes/agda-stdlib-classes.agda-lib" >> ~/.agda/libraries
          echo "${{ github.workspace }}/iog-agda-prelude/iog-prelude.agda-lib" >> ~/.agda/libraries
          echo "agda-stdlib-meta" >> ~/.agda/defaults
          echo "standard-library" >> ~/.agda/defaults
          echo "agda-stdlib-classes" >> ~/.agda/defaults
          echo "iog-prelude" >> ~/.agda/defaults

      - name: Verify Agda Files
        run: |
          cd specification
          agda --verbose=2 src/Semantics/Static/Coverage.agda
          agda --verbose=2 src/Overview.agda 

      - name: Notify on Failure
        if: failure()
        run: echo "❌ Agda verification failed!"
