name: Run compatibility tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use for running tests'
        required: true
        type: string
        default: "main"
          
  workflow_run:
    workflows: [ "Build, test and release compactc" ]
    types:
      - completed

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest-8-core-x64
    permissions:
      contents: read
    steps:
      - name: Checkout compactc repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Nix with cache
        uses: ./.github/actions/setup-nix-cache
        with:
          attic_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      # this should not have any impact on tests, as they are run in temp directories
      - name: Setup .npmrc
        run: |
          cd ./runtime
          echo "
          //npm.pkg.github.com/:_authToken=${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
          @midnight-ntwrk:registry=https://npm.pkg.github.com/
          " > .npmrc

      - name: Configure yarn
        run: |
          cd ./runtime
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}"
          echo 'checksumBehavior: update' >> ./.yarnrc.yml

      - name: Test compatibility
        timeout-minutes: 40
        env:
          GITHUB_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
        run: |
          cd tests-e2e
          nix develop .#compiler --command yarn install
          nix develop .#compiler --command yarn test:compatibility

      - name: Upload Junit test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-results-junit-summary
          path: tests-e2e/reports/test-report.xml

      - name: Upload event file
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: event-file
          path: ${{ github.event_path }}
