# NB: if this name changes, it must also be changed in notify-failed-scheduled
name: Compiler fuzzer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest-16-core-x64
    permissions:
      contents: read
      checks: write
    timeout-minutes: 45
    steps:
      - name: Checkout compactc repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Nix with cache
        uses: ./.github/actions/setup-nix-cache
        with:
          attic_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Compile
        run: |
          nix build

      - name: Test E2E
        run: |
          cd tests-e2e
          nix develop .#compiler --command yarn install
          nix develop .#compiler --command yarn test:fuzzer

      - name: Upload failed contracts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: failed-contracts
          path: tests-e2e/failed-contracts/

      - name: Publish Test Report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        if: always()
        with:
          name: Compactc E2E Tests Report
          path: |
            !(node_modules)/**/reports/test-report.xml
          reporter: jest-junit

      - name: Publish Test Summary
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          check_name: Compactc E2E Tests Results
          files: |
            **/reports/test-report.xml
            !(node_modules)/**/test-report.xml

      - name: Publish Test Summary Results
        uses: ctrf-io/github-test-reporter@7974087018bf4857cf5a9d78723e152038c3fa31 # v1.3.0
        with:
          report-path: 'tests-e2e/reports/ctrf-report.json'
          flaky-rate-report: 'true'
          pull-request: 'true'
          update-comment: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

