name: Generate documentation

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to grab docs from'
        required: true
        type: string
        default: 'release/midnight'
      docs_branch:
        description: 'Branch to merge with in midnight-docs'
        required: true
        type: string
        default: 'main'
      pr_description:
        description: 'PR description for docs'
        required: true
        type: string
        default: 'Example PR description for midnight-docs'
      draft_pr:
        description: 'Create PR as draft'
        required: false
        type: boolean
        default: false
    secrets:
      MIDNIGHTCI_PACKAGES_READ:
        required: true
      MIDNIGHTCI_PACKAGES_WRITE:
        required: true
      ATTIC_CACHE_TOKEN:
        required: true
      MIDNIGHTCI_REPO:
        required: true

permissions: {}

jobs:
  generate-docs:
    runs-on: ubuntu-latest-16-core-x64
    permissions:
      contents: read
    steps:
      - name: Checkout compactc repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.branch }}
          persist-credentials: false

      - name: Setup Nix with cache
        uses: ./.github/actions/setup-nix-cache
        with:
          attic_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Setup .npmrc
        run: |
          cd ./runtime
          echo "
          //npm.pkg.github.com/:_authToken=${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
          @midnight-ntwrk:registry=https://npm.pkg.github.com/
          " > .npmrc

      - name: Configure yarn
        run: |
          cd ./runtime
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}"
          echo 'checksumBehavior: update' >> ./.yarnrc.yml

      - name: Build runtime
        run: |
          nix build .#runtime.forPublish

      - name: Generate runtime docs
        run: |
          nix develop --command bash -c "cd ./runtime ; npm run build ; npm run generate-docs"

      - name: Checkout docs repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: "midnightntwrk/midnight-docs"
          token: ${{ secrets.MIDNIGHTCI_REPO }}
          path: "midnight-docs"
          ref: ${{ inputs.docs_branch }}
          persist-credentials: false

      - name: Manual Git Push
        env:
          MIDNIGHTCI_REPO: ${{ secrets.MIDNIGHTCI_REPO }}
          RUN_ID: ${{ github.run_id }}
        run: |
          cd midnight-docs
          git config user.name "midnight-ci"
          git config user.email "ci@midnight.network"
          git config --local --unset-all http.https://github.com/.extraheader || true
          git remote set-url origin "https://x-access-token:${MIDNIGHTCI_REPO}@github.com/midnightntwrk/midnight-docs.git"

          git checkout -b "compact-docs-update-${RUN_ID}"

          cp ../doc/ledger-adt.mdx docs/compact/data-types/ledger-adt.mdx
          cp ../doc/ledger-adt.mdx docs/compact/reference/ledger-adt.mdx

          cp ../doc/writing.mdx docs/compact/reference/writing.mdx
          cp ../doc/compact-reference.mdx docs/compact/reference/compact-reference.mdx
          cp ../doc/explicit-disclosure.mdx docs/compact/reference/explicit-disclosure.mdx
          cp ../doc/compact-grammar.mdx docs/compact/reference/compact-grammar.mdx
          cp ../doc/compact-keywords.mdx docs/compact/reference/compact-keywords.mdx

          cp ../doc/api/CompactStandardLibrary/exports.md docs/compact/standard-library/exports.md
          cp ../doc/api/CompactStandardLibrary/README.md docs/compact/standard-library/README.md

          cp ../doc/compiler-usage.mdx docs/compact/compilation-and-tooling/compiler-usage.mdx
          cp ../doc/formatter-usage.mdx docs/compact/compilation-and-tooling/formatter-usage.mdx
          cp ../doc/fixup-usage.mdx docs/compact/compilation-and-tooling/fixup-usage.mdx
          cp ../doc/dev-tool-usage.mdx docs/compact/compilation-and-tooling/dev-tool-usage.mdx

          cp -r ../doc/api/runtime/. ./api-reference/compact-runtime
          echo -e "# Compact runtime API\n\n$(cat ../doc/api/runtime/README.md)" > ./api-reference/compact-runtime/README.md

          python3 ../scripts/sync-css.py "../doc/custom-code.css" "src/css/custom.css"

          git add .
          git commit -m "Update compact documentation"
          git push origin "compact-docs-update-${RUN_ID}"

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.MIDNIGHTCI_REPO }}
          DRAFT_PR: ${{ inputs.draft_pr }}
          DOCS_BRANCH: ${{ inputs.docs_branch }}
          RUN_ID: ${{ github.run_id }}
          PR_DESCRIPTION: ${{ inputs.pr_description }}
        run: |
          DRAFT_FLAG=""
          if [ "$DRAFT_PR" = "true" ]; then
            DRAFT_FLAG="--draft"
          fi
          gh pr create \
            --repo midnightntwrk/midnight-docs \
            --base "$DOCS_BRANCH" \
            --head "compact-docs-update-${RUN_ID}" \
            --title "$PR_DESCRIPTION" \
            --body "PR: $PR_DESCRIPTION" \
            $DRAFT_FLAG
