name: Test workflow for release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string
      branch:
        description: 'Release branch'
        required: true
        type: string
      platform:
        description: 'Image with OS to run on'
        required: true
        type: string
      architecture:
        description: 'Processor architecture'
        required: true
        type: string
      artifact:
        description: 'Build artifact'
        required: true
        type: string

permissions: {}

jobs:
  e2e-test:
    name: Run e2e test for compactc on specific system
    runs-on: ${{ inputs.platform }}
    permissions:
      contents: read
    steps:
      - name: Set name of artifact
        run: |
          export ARTIFACT_NAME=compactc_${{ inputs.tag }}_${{ inputs.architecture }}
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Checkout compactc repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@midnight-ntwrk'
          node-version-file: '.nvmrc'

      - name: Download release artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.artifact }}

      - name: Run tests
        run: |
          mkdir temp-release
          mv ${{ env.ARTIFACT_NAME }}.zip temp-release
          cd temp-release
          unzip ${{ env.ARTIFACT_NAME }}.zip
          export COMPACT_HOME="$(pwd)"
          echo "COMPACT_HOME: $COMPACT_HOME"
          export PATH="$(pwd):$PATH"
          echo "PATH: $PATH"
          cd ../tests-e2e
          yarn install
          yarn test:release

      - name: Upload Junit test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-results-junit-${{ inputs.architecture }}
          path: tests-e2e/reports/test-report.xml

      - name: Upload CTRF test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-results-ctrf-${{ inputs.architecture }}
          path: tests-e2e/reports/ctrf-report.json
