name: Build, test and release vscode plugin

on:
  workflow_dispatch:
  push:
    tags:
      - 'compact-vsc-plugin-[0-9]+.[0-9]+.[0-9]+'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest-8-core-x64
    permissions:
      contents: read
    timeout-minutes: 45
    steps:
      - name: Checkout compactc repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Nix with cache
        uses: ./.github/actions/setup-nix-cache
        with:
          attic_token: ${{ secrets.ATTIC_CACHE_TOKEN }}

      - name: Compile
        run: |
          nix build .#compact-vscode-extension

      - name: Upload plugin
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: compact-vscode-plugin
          path: result/compact-*.vsix

      - name: Extract Version
        run: |
          echo "Full ref name: ${{ github.ref_name }}"
          VERSION=$(echo "${{ github.ref_name }}" | grep -oP '\d+\.\d+\.\d+')
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Use Extracted Version
        run: |
          echo "Version extracted: ${{ env.version }}"

      - name: Create Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          repository: midnight-ntwrk/artifacts
          tag_name: ${{ github.ref_name }}
          name: Compact VSC Plugin ${{ env.version }}
          draft: false
          prerelease: false
          files: result/compact-*.vsix
          token: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
          body: Compact VSC Plugin ${{ env.version }}
