name: VSC Plugin Installation Tests

on:
  workflow_dispatch:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install code-server
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh

      - name: Package plugin
        run: |
          cd ./editor-support/vsc/compact
          yarn install --frozen-lockfile
          yarn package

      - name: Install and uninstall extension
        run: |
          cd ./editor-support/vsc/compact
          EXTENSION=$(ls *.vsix)

          echo "Install extension"
          code-server --install-extension "$EXTENSION" | tee installation.log 2>&1
          if ! cat installation.log | grep -q -v "successfully installed"
          then
            echo "Failure"
            exit 1
          fi
          
          echo "List extensions"
          code-server --list-extensions --show-versions | tee list_extensions.log
          EXT_ID=$(cat list_extensions.log | grep "compact" | cut -d '@' -f 1)
          
          echo "Uninstall extension"
          code-server --uninstall-extension "$EXT_ID" | tee uninstallation.log 2>&1
          if ! cat uninstallation.log | grep -q -v "successfully uninstalled"
          then
            echo "Failure"
            exit 1
          fi
